### ISSUE TITLE
geographical queries

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#104]
afaik, while crateDB supports that quite well, there is no way to support geo queries from any API.

see *geo graphical queries* in the spec:
* http://fiware.github.io/specifications/ngsiv2/stable/

and cratedb support:
* https://crate.io/docs/crate/reference/en/latest/general/dql/geo.html

the following ones should be easy to implement:
* `georel=intersects`. Denotes that matching entities are those intersecting with the reference geometry.
    * maps to `MATCH (column_ident, query_term) using intersects`
* `georel=coveredBy`. Denotes that matching entities are those that exist entirely within the reference geometry. When resolving a query of this type, the border of the shape must be considered to be part of the shape.
    * maps to `MATCH (column_ident, query_term) using within`

A bit more complex:
* `georel=near`. The near relationship means that matching entities must be located at a certain threshold distance to the reference geometry. It supports the following modifiers: `maxDistance`. Expresses, in meters, the maximum distance at which matching entities must be located. `minDistance`. Expresses, in meters, the minimum distance at which matching entities must be located.

still it seems there are quite some hints here on how to solve that:
https://crate.io/a/geospatial-queries-with-crate-data/

**Comment by c0c0n3** [comment]
see #111

**Comment by c0c0n3** [comment]
closed by #111
