### ISSUE TITLE
Complete implementation of /attrs endpoints in API

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#118]

**Comment by daminichopra** [comment]
Hi @taliaga @c0c0n3 , Please assign this issue to me. Thank you :)

**Comment by c0c0n3** [comment]
done, thanks!!!

**Comment by c0c0n3** [comment]
hi @daminichopra, I'm curious though, what's your use case? i.e. what do you need this for? I'm struggling to think of a good use case. In fact, querying an attribute across **all** entities assumes you know beforehand this makes sense, i.e. you know that:

1. there exist an attribute `x` shared by a set of entities `E = { e ∈ DB | ∃ e.x }`.
2. the **meaning** of `x` is the same **for all** entities in `E`.

I reckon (2) is key here to avoid comparing apples and oranges. For example, think of a scenario where we have two entities in our DB `Air` and `Device` both with a `quality_index` attribute:

* `Air.quality_index` = carbon dioxide per cubic meter
* `Device.quality_index` = failures per minute

The attributes are **unrelated** but happen to have the same name. A call to `/attrs` would return both sets of attribute values but how would you handle such data, e.g. what kind of **meaningful** operation would you apply on those values?

So in general, we can't assume (2) holds true. In other words, at any given time `E` may contain entities `e1` and `e2` whose attributes `x` are **unrelated**. Given this, the caller must be able to narrow the set `E` to that of all entities for which (2) is true, i.e. I think the API should let the caller define a search space

    S = { e ∈ DB | ∃ e.x ∧ p(e) }

where `p: Entities --> Bool` is a predicate ensuring `S` only contains those entities where `x` has the same **meaning**. For example, `p` could filter by entity type as in

    p(e) = True <=> e.type ∈ { Air, Water }

Anyway, chances are I'm missing something. Like I said if you have a good use case for an **unrestricted** `/attrs` API endpoint, I'd love to hear about it :-)

**Comment by daminichopra** [comment]
Hi @c0c0n3 , I have raised PR for API implementation /v2/attrs.
I would like to suggest to create a new issue for https://github.com/smartsdk/ngsi-timeseries-api/issues/118#issuecomment-581325646 
Thank you :)

**Comment by c0c0n3** [comment]
Hi @daminichopra!

> I would like to suggest to create a new issue for #118 (comment)

Not necessary for now. I see your implementation (#294) actually lets clients filter by type which is great. So a client can specify "entity type" filters as in the example I gave earlier:

    p(e) = True <=> e.type ∈ { Air, Water }

I've had a second thought about implementing a filter based on a more generic predicate `p: Entities --> Bool` since that means changing the underlying query building logic which is anything but trivial. That was a long way to say: don't bother :-)

**Comment by c0c0n3** [comment]
closed by #294
