### ISSUE TITLE
Support attributes metadata

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#12]
Attributes metadata are defined in
http://docs.orioncontextbroker.apiary.io/#introduction/specification/terminology

This information is currently not saved in the DB, so it's lost in the dump/load.

**Comment by chicco785** [comment]
question is, how to track what is metadata and what is not? separate table? prefix in the column name?

**Comment by taliaga** [comment]
As a comment: in _get_time_index(payload): the `time_index` from metadata should have higher priority than `dateModified`

**Comment by taliaga** [comment]
we need to understand if metadata typically changes throughout time or not. If not, we may find more efficient ways of treating static data. There's already a metadata table for each entity type, this could be a place to land metadata.

**Comment by chicco785** [comment]
I would assume they may change over time.


Dr. FEDERICO MICHELE FACCA
CTO
0041 78 807 58 38
Martel Innovate  -  Professional support for innovation projects 	
Click to download our innovators' insights! 	
Follow Us on Twitter
