### ISSUE TITLE
Publish 0.5 API to SwaggerHub 

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#121]
We have to publish the new 0.5 API to SwaggerHub since it documents the new geo query parameters and the fact we now support the whole NGSI geo query spec. After doing that, update the link in the [data retrieval section][manual-data-retrieval] of the user manual that points to the published API.

[manual-data-retrieval]: https://github.com/smartsdk/ngsi-timeseries-api/blob/v0.5rc/docs/manuals/user/index.md#data-retrieval

**Comment by taliaga** [comment]
Done, it's at https://app.swaggerhub.com/apis/smartsdk/ngsi-tsdb/0.2.

I wanted to add you to the smartsdk organisation but unless I'm missing something, unfortunately the free swagger plan allows only one "member".
