### ISSUE TITLE
Handle text attributes with no value

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#125]
QL bombs out if an entity contains an attribute of type `Text` which has no `value` field. E.g.

    export ENDPOINT=http://0.0.0.0:8668/v2/notify
    curl -v -X POST ${ENDPOINT} -H 'Content-Type: application/json' -d'
    {
        "data": [
            {
                "id": "d:1",
                "type": "d",
                "a1": {
                    "type": "Number",
                    "value": 123
                },
                "a2": {
                    "type": "Text"
                }
            }
        ]
    }
    '

results in:

    HTTP/1.0 500 INTERNAL SERVER ERROR
    Content-Type: application/problem+json
    Content-Length: 252
    Server: Werkzeug/0.14.1 Python/3.6.6
    Date: Thu, 20 Dec 2018 10:49:03 GMT

    {
        "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
        "status": 500,
        "title": "Internal Server Error",
        "type": "about:blank"
    }

**Comment by c0c0n3** [comment]
Commit f6ee603 fixes the issue, but I'm not quite sure into which branch to merge it---should we have a new 0.5.1 release or should this fix be included in 0.6?

**Comment by c0c0n3** [comment]
@chicco785 On another note, in the above commit, you'll also find tests to verify we can actually add attributes to existing entities. Essentially this is possible because in Crate if you try to create the same table twice, the resulting table will contain the union of the columns declared in the two create table statements. E.g.

    create table if not exists etx
    (entity_id string, entity_type string, time_index timestamp, a1 float)
    
    create table if not exists etx
    (entity_id string, entity_type string, time_index timestamp,  a1 float, a2 string)

will result in an `etx` table with both columns `a1` and `a2`. Similarly

    create table if not exists ety
    (entity_id string, entity_type string, time_index timestamp, a1 float)

    create table if not exists ety
    (entity_id string, entity_type string, time_index timestamp, a2 string)

will result in an `ety` table with both columns `a1` and `a2`.

**Comment by chicco785** [comment]
> Commit [f6ee603](https://github.com/smartsdk/ngsi-timeseries-api/commit/f6ee60364223941d5679b8fb6551b0d98d749eec) fixes the issue, but I'm not quite sure into which branch to merge it---should we have a new 0.5.1 release or should this fix be included in 0.6?

0.6 is fine!

**Comment by chicco785** [comment]
> @chicco785 On another note, in the above commit, you'll also find tests to verify we can actually add attributes to existing entities. Essentially this is possible because in Crate if you try to create the same table twice, the resulting table will contain the union of the columns declared in the two create table statements. E.g.
> 
> ```
> create table if not exists etx
> (entity_id string, entity_type string, time_index timestamp, a1 float)
> 
> create table if not exists etx
> (entity_id string, entity_type string, time_index timestamp,  a1 float, a2 string)
> ```
> will result in an `etx` table with both columns `a1` and `a2`. Similarly
> 
> ```
> create table if not exists ety
> (entity_id string, entity_type string, time_index timestamp, a1 float)
> 
> create table if not exists ety
> (entity_id string, entity_type string, time_index timestamp, a2 string)
> ```
> will result in an `ety` table with both columns `a1` and `a2`.

great, i recall from the discussions with @taliaga that this was somehow handled and good that you had a test, so if crate behaviour change, we will find it out ;)

**Comment by c0c0n3** [comment]
cool, added issue to 0.6 milestone.

**Comment by c0c0n3** [comment]
closed by #126
