### ISSUE TITLE
automatic casting to NGSI data type

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#129]
when a value does not match the NGSI data type it should be casted it, only if the cast fails, error should be returned.

the implementation of this functionality is to be evaluated, an alternative solution could be in fact to give priority to the datatype of the value and "cast" the NGSI type to it. the two solutions are obviously incompatible.

**Comment by chicco785** [comment]
see also discussion in #123

**Comment by c0c0n3** [comment]
closed by #142
