### ISSUE TITLE
Support multiple endpoints for crate

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#13]
Supposing that you have a CRATE cluster and that each node expose different endpoints, it would be useful a sort of "roundrobin" process to connect to the different hosts in case one of them is not reachable.
This may not be an issue in Docker Swarm, where hopefully, using healthchecks, the swarm remove and endpoint from the "discovery" feature if it is not healthy.

**Comment by taliaga** [comment]
Revisiting this, this sounds like not a problem to be solved within QL, right?
