### ISSUE TITLE
[MUST] Credits are missing

### ISSUE THREAD

**Issue by jason-fox** [smartsdk/ngsi-timeseries-api#137]
According to the contribution requirements, credit must be given to developers who contribute to the development of each component. A simple way to do this is to add and maintain a  [CREDITS](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/CREDITS) file.

The list of previous contributors can be obtained using the following command:

```console
git shortlog -cse
```

- MUST Requirement from the TSC

**Comment by taliaga** [comment]
Hi,

While I agree with the need of thanking people, I just don't quite see the point of having this file, considering this info is already in git, or even https://github.com/smartsdk/ngsi-timeseries-api/graphs/contributors.

That being said, I do want to keep consistency with the rest. Note however such command doesn't pick all contributors. Would the output of `git shortlog -sn` work for the requirements? Which alternative would you recommend?

Thanks!

**Comment by jason-fox** [comment]
The original wording in the requirements document when this issue was raised stated _"List **all contributors** and do it like Node.js"_ , there is an PR to alter this  see - https://github.com/Fiware/contribution-requirements/pull/39

The proposed update would state _"List **major contributors only** and add a git short log for the rest like [one of these](https://github.com/Fiware/contribution-requirements/pull/39#issuecomment-457547595)"_ , so take your pick, Node.js style or Git Short log style
