### ISSUE TITLE
Support multi-tenancy using service path concept of context broker

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#14]
When we deal with different scenarios sharing a common infrastructure, but we do not want them to share access to data, we need to find a way to isolate the data.
A simple solution, as the one used in context broker vs mongodb, is to have one database for tenant (identified by the service-path in the header request).

**Comment by taliaga** [comment]
Change DB_NAME = "ngsi-tsdb" to `default`, as suggested in https://github.com/smartsdk/ngsi-timeseries-api/pull/49

**Comment by taliaga** [comment]
Fixed by https://github.com/smartsdk/ngsi-timeseries-api/pull/65
