### ISSUE TITLE
Error when receiving empty value for datetime types

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#145]
When notifications come with attributes of type DateTime (or ISO8601) and no value, QL fails to insert a default "null".

For reference, see https://github.com/smartsdk/ngsi-timeseries-api/pull/122/files

**Comment by pooja1pathak** [comment]
Hi @taliaga @c0c0n3 ,
Is this issue fixed by PR https://github.com/smartsdk/ngsi-timeseries-api/pull/150 ? or need to be fixed?

**Comment by c0c0n3** [comment]
@pooja1pathak yes good catch, PR #150 fixes it, we just plain forgot to close this issue. Thanks!
closed by #150.
