### ISSUE TITLE
Log Level

### ISSUE THREAD

**Issue by StephaneRouxNCA** [smartsdk/ngsi-timeseries-api#160]
How can I change log level?

**Comment by tstorek** [comment]
Hi,
are there any new on this? We would like to use Qunatumleap in a project but the logging in this way is quite unhandy.

Thanks

**Comment by c0c0n3** [comment]
Hi @tstorek, nice hearing from you!

> are there any new on this?

Sadly no. We do recognise this is something that needs to be done but have no dev capacity at the moment. Hopefully that'll change in the new year :-)

As always, contributions are very welcome!!!
