### ISSUE TITLE
CrateDB Plugin for Grafana 

### ISSUE THREAD

**Issue by scjimenez** [smartsdk/ngsi-timeseries-api#166]
Hi,

with our latest effort, the PostgreSQL implementation of Grafana works fine with CrateDB. Hence we skip the Grafana Datasource Plugin for CrateDB and move over to the PostgreSQL data source. 

May I ask you to do so as well and furthermore adapt this page https://smartsdk.github.io/ngsi-timeseries-api/admin/grafana/?

Thanks a lot in advance.

Best, Stephanie

**Comment by taliaga** [comment]
Hi Stephanie, for sure we'll do the switch.
Thank you!

**Comment by taliaga** [comment]
Consider [this post](https://crate.io/a/pair-cratedb-with-grafana-an-open-platform-for-time-series-data-visualization/) while updating the docs.

**Comment by scjimenez** [comment]
Thanks a lot for the switch, that's awesome :) May I ask you to update [this page of yours](https://smartsdk.github.io/ngsi-timeseries-api/admin/grafana/) as well, please? In case needed: Please find some information about pairing CrateDB with the latest Grafana version [in this blog post.](https://crate.io/a/pair-cratedb-with-grafana-6-x-an-open-platform-for-time-series-data-visualization/). Thanks a lot in advance.
