### ISSUE TITLE
Authentication / Authorisation Proxy

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#17]
May not be a "direct" issue related to QuantumLeap, but a side one.
When accessing from Grafana (assuming we use the existing driver) there should be away to provide a sort of access control on tables and rows in side a table.

**Comment by taliaga** [comment]
Side mental note, from the docs: "In the standard edition of CrateDB, there is no notion of access control and everybody can see and manipulate tables in every schema. In the Enterprise Edition of CrateDB, you can use privileges to control access to schemas."
