### ISSUE TITLE
Bug: throttling cannot be set to zero

### ISSUE THREAD

**Issue by dcalvoalonso** [smartsdk/ngsi-timeseries-api#177]
Using the subscribe endpoint as described in https://github.com/smartsdk/ngsi-timeseries-api/blob/master/specification/quantumleap.yml#494, if the throttling query parameter is set to zero, QL creates the subscription in the context broker using the default value (1).

**Comment by taliaga** [comment]
Good spot, thanks for the report!

**Comment by taliaga** [comment]
Forgot to mention the fix can be tested with `smartsdk/quantumleap:rc` Docker image until `0.6.1` is out.
