### ISSUE TITLE
Data persistence even after removing subscription

### ISSUE THREAD

**Issue by pooja1pathak** [smartsdk/ngsi-timeseries-api#195]
According to the [documentation](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/docs/manuals/user/index.md) which states that ```Historical data for each entity type will be persisted as long as the subscription is active, correctly configured and the entity in the notification is NGSI compliant.``` It should be concluded that the data in QuantumLeap should exist as long as subscription is active or present in Orion.

But as per my investigation and observation it does not behave as expected. Data in the QuantumLeap persist even after deletion of subscription or changing status from ```active``` to ```inactive```.

Steps that I have followed:
1. Created an entity at orion.
2. Subscribed that entity to QuantumLeap by /v2/subscription API.
3. Updated the entity attribute.
4. Unsubscribed the QunatumLeap.
5. Execute GET for that entity using QL API /v2/entities/{entityId}

I have also checked by updating subscription "status" from "active" to "inactive".
But I am able to view data.

I have also checked the code for validating the Subscription ID for the /v2/notify request but I am unable to find any.

So, should it be concluded that the statement mentioned in the documentation is incorrect and should be updated according to the current behavior.

**Comment by chicco785** [comment]
The statement refers to the fact that no new data is persisted if no subscription is active. You need to remove data calling the proper endpoint if you don’t want it to be stored anymore.

**Comment by taliaga** [comment]
The use of the English expression "as long as" there is to indicate that the mentioned conditions are prerequisites for data persistence. I.e., it means "provided that", not "for the duration of". I understand why this may be a source of confusion, so we could rephrase the sentence if you agree.

I believe QL should never delete data when subscriptions are deactivated/deleted in Orion.
