### ISSUE TITLE
return not found for query attribute, but the attribute is there

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#206]
**Describe the bug**
An attribute that is listed in the single entity query is not returned in the attr query.

**To Reproduce**
Steps to reproduce the behaviour:
1. Send this payload `https://api.s.orchestracities.com/timeseries/v2/entities/urn:ngsi-ld:AirQualityObserved:lugano-2689/attrs/airQualityIndex/value?lastN=10`
2. See error:
```
{
    "description": "No records were found for such query.",
    "error": "Not Found"
}
```

**Environment (please complete the following information):**
 - CrateDB: 3.3.3

**Comment by c0c0n3** [comment]
closed by #210.
