### ISSUE TITLE
issues with multi entity notification (wrong servicepath created)

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#208]
**Describe the bug**
When a multiple notification is sent, the service path created is a comma separated version of all servicepaths of the entities.
It could be that the header sent by orion is exactly that. We should then split it and attach it one for entity.

entity_id | entity_type | fiware_servicepath | powerstate | time_index | timeinstant
-- | -- | -- | -- | -- | --
urn:ngsi-ld:Streetlight:sl-6 | Streetlight | /Diorama,/Diorama,/Diorama,/Diorama,/Diorama,/Diorama | NULL | 1560425955297 (2019-06-13T11:39:15.297Z) | NULL
urn:ngsi-ld:Streetlight:sl-1 | Streetlight | /Diorama,/Diorama,/Diorama,/Diorama,/Diorama,/Diorama | NULL | 1560422941000 (2019-06-13T10:49:01.000Z) | 1560422941000 (2019-06-13T10:49:01.000Z)
urn:ngsi-ld:Streetlight:sl-3 | Streetlight | /Diorama,/Diorama,/Diorama,/Diorama,/Diorama,/Diorama | NULL | 1560422941000 (2019-06-13T10:49:01.000Z) | 1560422941000 (2019-06-13T10:49:01.000Z)
urn:ngsi-ld:Streetlight:sl-2 | Streetlight | /Diorama,/Diorama,/Diorama,/Diorama,/Diorama,/Diorama | NULL | 1560422941000 (2019-06-13T10:49:01.000Z) | 1560422941000 (2019-06-13T10:49:01.000Z)
urn:ngsi-ld:Streetlight:sl-5 | Streetlight | /Diorama,/Diorama,/Diorama,/Diorama,/Diorama,/Diorama | NULL | 1560425955297 (2019-06-13T11:39:15.297Z) | NULL
urn:ngsi-ld:Streetlight:sl-4 | Streetlight | /Diorama,/Diorama,/Diorama,/Diorama,/Diorama,/Diorama | NULL | 1560360355000 (2019-06-12T17:25:55.000Z) | 1560360355000 (2019-06-12T17:25:55.000Z)

**Environment (please complete the following information):**
 - CrateDB 3.3.3

**Comment by c0c0n3** [comment]
closed by #363
