### ISSUE TITLE
don't store entries where all values are null

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#209]
**Is your feature request related to a problem? Please describe.**

When you first register an iot device, a registration with empty values is sent to the context broker. as result a corresponding notification may be sent to quantumleap. such notification should not be used, given that no data will be in it.

**Comment by Chandradeep-NEC** [comment]
@chicco785 @c0c0n3 @taliaga 
If no one is working on this issue, then lease assign us

**Comment by daminichopra** [comment]
Hi @chicco785 , I am working on this issue and i want to confirm if payload contains both **"null"** and **some value** as Key value in payload for attributes in that case QL will filter out such entries and will not be stored in CrateDB.

**Comment by chicco785** [comment]
@daminichopra the idea is to ignore only entities where all attribute values are null (except entityType and entityId).

**Comment by daminichopra** [comment]
Hi @chicco785 , Please close this issue as it is Fixed. Thank you :)

**Comment by c0c0n3** [comment]
cool, thanks for reminding us :-)
closed by #278
