### ISSUE TITLE
Upgrade test env to Crate 3.3.3

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#211]
We've recently upgraded our prod Crate cluster to Crate version 3.3.3 but we're not yet using this version in our dev test environment.

**Proposed solution**
Use Crate 3.3.3 in all our docker files.

**Comment by chicco785** [comment]
let's check the matrix approach to test multiple version of crate!
https://github.com/smartsdk/mongo-rs-controller-swarm/blob/master/.travis.yml

**Comment by daminichopra** [comment]
Hi @chicco785 , Please assign this issue to me.

**Comment by daminichopra** [comment]
Raised [PR#313](https://github.com/smartsdk/ngsi-timeseries-api/pull/313)
