### ISSUE TITLE
Coverage tool integration with Travis for quantumleap

### ISSUE THREAD

**Issue by ghost** [smartsdk/ngsi-timeseries-api#215]
Code coverage shows which lines of source code have been tested and which lines of your source code have not been tested.
It will help to improve code quality. Whenever a new PR comes, it is important to find the code coverage before merging it into the master code. 

So, there should be a proper coverage tool integration available for quantumleap repository.
I'd suggest to integrate existing Travis ci with some coverage tool.

Could you please provide your opinion for the same?

**Comment by SourabhChourasiya-NEC** [comment]
Hello @c0c0n3, @chicco785, @taliaga Sir

I am investigating for Coveralls, CodeCov and CodeClimate with coverage.py. Could you please provide your opinion for code coverage tools(Coveralls, CodeCov and CodeClimate) or according to you which one is suitable for the same?

As per my suggestion, we can use coveralls with Travis for the same. 
Please provide your valuable comments.

Thanks

**Comment by taliaga** [comment]
Hi @SourabhChourasiya-NEC , thanks for taking the initiative here. I don't have a strong preference over which of those to go with, I am happy to trust your judgement. I assume you have a criteria to pick one. We'll be happy to hear about your criteria and your findings!

If it helps, here are some points that I would consider:
- Easy to use (not only to put in place, but also to let us extract the most important result (IMO): if the new branch being merged is improving or worsening the current codebase health).
- Free plan for open source projects
- Power of configuration (e.g. bonus points if you can choose on which branches to run, regardless of where those branches are aimed towards).

**Comment by SourabhChourasiya-NEC** [comment]
fixed in #221
