### ISSUE TITLE
Not able to access subscribe API of quantumleap with WSO2 API Manager

### ISSUE THREAD

**Issue by SwatiNEC** [smartsdk/ngsi-timeseries-api#222]
Hi 

I am accessing QuantumLeap APIs via WSO2 APIM using mediator and policy files. The GET entities API executes successfully. But I am facing an issue while executing the subscribe API of QuantumLeap via WSO2 API Manager, i.e., Quantumleap becomes unresponsive for subscribe API, and in this unresponsive duration we are not able to access any other API of QL directly.
But after some time the timeout error occurs for Subscribe API on WSO2 APIM and then we are able to access any API of QL directly.

Versions:
WSO2 APIM - 2.6.0
WSO2 IS - 5.7.0
QuantumLeap - 0.5.0

Note: I have checked the logs of WSO2 APIM and confirmed that WSO2 APIM sends request to QuantumLeap for “subscribe API”, but QuantumLeap becomes unresponsive to the request and there are no error logs at QuantumLeap side as well as WSO2 APIM side.
Could anyone help in finding the root cause of this issue.

**Comment by taliaga** [comment]
Hi,

I have never tried WSO2. We should understand if it's a QL-only or an integration issue with WSO2.

Could you reproduce the problem with a simple local docker-based deployment of QL? `/subscribe` should work for you in this setting.

Note that the '/subscribe` endpoint is just a convenience to get your subscription created in Orion. It makes QL create a request to Orion, so maybe this request is being blocked in your deployment environment.

**Comment by SwatiNEC** [comment]
HI @taliaga 

It is an integration issue with WSO2 when we use policy based authorization on wso2.

`Could you reproduce the problem with a simple local docker-based deployment of QL?`
yes /subscribe API of QL is working properly without WSO2. I am facing this issue only with WSO2.

Is there any deployment server used by QL?

**Comment by taliaga** [comment]
Good first check. 
Did you happen to investigate the hypothesis of QL's request to Orion being blocked by WSO2? 
Not sure I understand your last question. We've been deploying QL in Docker Swarm clusters on Openstack, Kubernetes clusters on AWS and vSphere. Never with WSO2 though, so I'm not sure how I can be of further help.
