### ISSUE TITLE
Insertion date != Observation date

### ISSUE THREAD

**Issue by tomsluyts** [smartsdk/ngsi-timeseries-api#223]
Is there a way in quantum leap to distinguish between insertion date and observation date? 

STH has the difficulty that for instance the querying API uses the insertion date as the basis for time related queries. This leads for instance to issues when replaying historical data to get it up to date - in these cases the insertion date is not very relevant. Basically insertion date only has operational uses, it's the observation date that most people will be interested in when looking up historical series.

**Comment by taliaga** [comment]
Hi there!

There are many dates in the nature of the problem and things can get a bit confusing quite easily (for me at least).

For the queries, QuantumLeap will use the `time_index` column. Which date field that column persists is something you can configure and it's explained (hopefully) [in the Time Index part of Data Insertion in the docs](https://quantumleap.readthedocs.io/en/latest/user/#data-insertion). If something is confusing there, let's make it better!

In short, for historical reasons QL started being developed using the dateModified attribute (a special attribute Orion Injects in the notifications if you ask for that). That is always available, but for some use-cases can be far from when the measurement was done. So, QL extended support for times added by the agents, etc. 

Some NGSI models have a specific attribute to indicate the date where the observation was made (`dateObserved`). If that's your case, you could instruct QL to use that attribute with the use of the `Fiware-TimeIndex-Attribute` headers (see first option listed there in the docs). NOTE: I've seen `dateObserved` used as a range ("timestamp1/timestamp2"), but for now QL supports only a single valid `DateTime` (1 point in time).

**Comment by tomsluyts** [comment]
Thanks that's a clear answer. It would be nice if QL would support ranges, or would at least have a way to handle them, because the NGSI datamodel also supports them but for us it's not a must.
