### ISSUE TITLE
Support use of " wrapping fromDate and toDate

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#225]
**Describe the bug**

Parameters dateFrom and dateTo of several API methods require a date in ISO format. If such paramter goes as "YYYY-mm-ddThh:mm:ss" instead of just YYYY-mm-ddThh:mm:ss (i.e. with wrapping "") QL does not recognize the dates.

**Comment by pooja1pathak** [comment]
Hi @taliaga @c0c0n3 , I want to contribute for this issue. Please assign it to me.

**Comment by c0c0n3** [comment]
@pooja1pathak just assigned to you, thanks :-)))

**Comment by pooja1pathak** [comment]
@c0c0n3 , as PR #285 is merged, this issue can be closed.

**Comment by c0c0n3** [comment]
@pooja1pathak whoops, thanks for reminding me!

closed by PR #285
