### ISSUE TITLE
/ui/ endpoint no longer available since 0.6.2

### ISSUE THREAD

**Issue by jaimeventura** [smartsdk/ngsi-timeseries-api#229]
Since 0.6.2, with the update to Connexion 2.x, /ui/ endpoint no longer available.

You need to include/install 'connexion[swagger-ui]', as it no longer includes Swagger UI by default.

**Comment by c0c0n3** [comment]
@jaimeventura thank you so much for reporting this along with how to fix it, much appreciated! PR #244 implements your fix and now the Swagger UI is available again at `/v2/ui/`.

**Comment by c0c0n3** [comment]
closed by #244
