### ISSUE TITLE
Why subscribe API use query parameters

### ISSUE THREAD

**Issue by SwatiNEC** [smartsdk/ngsi-timeseries-api#234]
Hi

I have a query regarding the implementation of notify and subscribe API. subscribe API uses query parameter as payload while notify API uses body as payload.
Could you please tell me why the implementation of both API is different?

**Comment by c0c0n3** [comment]
Hi @SwatiNEC,

The reason why each endpoint has a different interface is that those endpoints serve different purposes. The `notify` endpoint is where Orion sends entity updates to QuantumLeap, whereas `subscribe` is a QuantumLeap-specific convenience endpoint to register QuantumLeap for notifications with Orion---i.e. to create a subscription in Orion that points back to QuantumLeap's `notify` endpoint. If that sounds confusing, read on, hope the mist will clear :-)

QuantumLeap and Orion stand in a producer-consumer relationship. Orion, the producer, can push selective entity state change updates to any consumer you register with Orion---QuantumLeap is one such consumer. This registration process happens through Orion's subscription endpoint. As part of the registration process, you specify a consumer's URL where Orion can `POST` updates---this URL is usually referred to as the "notify" endpoint. In QuantumLeap, the notify endpoint is at `/v2/notify`. For Orion to be able to send status updates, the consumer (QuantumLeap in our case) has to implement the notify endpoint as required by the [NGSI spec](https://fiware.github.io/specifications/ngsiv2/stable/). In other words, we, as QuantumLeap implementers, don't have a choice about what the notify endpoint interface should look like, it's got to be what Orion expects.

Perhaps confusingly, QuantumLeap also has a `subscribe` endpoint whose purpose is to make it easier, at least for common cases, to register your QuantumLeap server with Orion for entity updates. This QuantumLeap endpoint is at `/v2/subscribe`. When you use this endpoint, QuantumLeap registers itself with Orion---i.e. creates a subscription at the Orion server you specify.

I reckon an example will help at this point. Say we have a few weather stations that send data to Orion through IoT agents and device data gets turned into NGSI entities of type `WeatherStation`. We'd like Orion to send QuantumLeap device data whenever it's received from any of the connected weather stations. To get the job done, we can use Orion's subscribe endpoint to create the subscription with an HTTP POST as below:

    POST /v2/subscriptions
    Host: your.orion.server
    Content-Type:application/json
    ...

    {
        "subject": {
            "entities": [{
                    "idPattern": ".*",
                    "type": "WeatherStation"
                }]
        },
        "notification": {
            "http": {
                "url": "http://your.quantumleap.server/v2/notify"
            }
        }
    }

Alternatively, you could use QuantumLeap's `subscribe` endpoint to do the same---formatted for readability:

    POST /v2/subscribe?
          orionUrl=http://your.orion.server/v2 &
          quantumleapUrl=http://your.quantumleap.server/v2 &
          entityType=WeatherStation
          
    Host: your.quantumleap.server
    ...

Either way, you'll get your subscription created in Orion. Now when some measurements come into Orion from any of the connected weather stations, Orion will `POST` the corresponding NGSI entity to the QuantumLeap notify endpoint as in the example below:

    POST /v2/notify
    Host: your.quantumleap.server
    Content-Type:application/json
    ...

    {
        "id": "WeatherStation:5",
        "type": "WeatherStation",
        "temperature": { "type": "Number", "value": 20 }
        ...
    }

Admittedly, QuantumLeap's subscribe interface is a bit unorthodox in its use of query params rather a `POST` body, but then again, I hope you'll appreciate this endpoint has a very different semantics than the QuantumLeap's notify endpoint. Of course, your mileage may vary :-)
