### ISSUE TITLE
Enable Coveralls integration

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#235]
**Is your feature request related to a problem? Please describe.**
After merging #221 into master, there are still a couple manual of steps to enable Coveralls integration with GitHub and Travis.

**Describe the solution you'd like**
@chicco785 @taliaga follow the instructions on #221 to log into Travis and Coverall, taking care of using the **organisation** account so that the settings don't get tied to your personal GitHub account.

**Describe alternatives you've considered**
I tried doing this myself using my personal GitHub account but then it looked like all settings were tied to my account---e.g. email, commit history, etc.

**Additional context**
N/A

**Comment by chicco785** [comment]
i think i covered all stesp

**Comment by c0c0n3** [comment]
excellent, thanks! closed by #236
