### ISSUE TITLE
CrateDB 4 Upgrade

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#256]
### The problem
With the CrateDB 4.x series out since June 2019, we should consider upgrading at some point. 
Currently we support version `3.3` and it doesn't look like that upgrading to `4.x` is going to be a walk in the park for us. In fact, some of the SQL statements we generate rely on features that were dropped in Crate `v4` (see e.g. #254) and it'd be a good idea to review the rest of the SQL we generate too. Also, we might have to migrate prod tables since according to the Crate docs:

> Tables that were created prior CrateDB 3.x will not function with 4.x and must be recreated before moving to 4.x.x.

Do we have any prod tables that we created with Crate `2`? Did the upgrade to `v3` automatically changed their format so that they'll be compatible with `v4`? Um, I doubt it...

### Proposed solution
Test each and every SQL statement we generate with Crate 4 and fix what breaks. Figure out if we need a data migration too. Then do the upgrade.

### Alternatives
If testing SQL statements turns out to be too time consuming, we should consider if this is a good time to re-engineer the translators (both Crate and Timescale) to use ASTs instead of string manipulation.

**Comment by chicco785** [comment]
@c0c0n3 as first action, i would in the readme the version supported of crate and timescale

**Comment by chicco785** [comment]
`ON CONFLICT (column_ident [, ...]) DO UPDATE SET { column_ident = expression` update may not be that painful. Yes we had some release using crate 2.x. But i am not sure anyone is still using it.

**Comment by c0c0n3** [comment]
> not be that painful.

Yep, as long as it's the only thing to change, but we should test the rest too :-)

**Comment by tstorek** [comment]
Hi,
is there any update on this? From my perspective crate 4.x is slighly easier adminstrate and to scale than v3.x. Especially from the documentation point of view it seems easier. But maybe this also goes together with #258 which would make quantumleap more independent from the database engine itself.

Cheers

**Comment by c0c0n3** [comment]
Hi @tstorek,

No, we haven't managed to tackle this yet. We're understaffed at the moment, so this will probably have to wait until next year---of course, contributions are welcome! Re: InfluxDB, we have no plans to support it at the moment since it's missing some critical (to us!) features, see [this comment](https://github.com/smartsdk/ngsi-timeseries-api/issues/258#issuecomment-541308721) to #258.

Sorry to disappoint you, but like I said we'd really need an extra pair of hands to get this off the ground...

**Comment by pinkerltm** [comment]
We would also very much appreciate if crate 4.x gets supported as we already use it as a component, currently persist context data with our very own glue code (but without an API to query the timeseries) and downgrading to 3.x isn't really an option at our stage.

As much as I would like to contribute on this, I doubt that my python skills will be helpful here, but at least I have forked the repo to examine if there is anything simple I can do.

**Comment by chicco785** [comment]
@pinkerltm I suspect the issue is not much about python skills, at least to introduce base support. At the moment, as you can read from the thread, is not a priority internally. Of course contributions are welcome. If that's really something extremely important and urgent to you, we can explore some commercial support option, but we will have to check if allocations allow for that.

**Comment by c0c0n3** [comment]
@pinkerltm 

> examine if there is anything simple I can do.

You could try patching SQL statement generation like @chicco785 explained in an [earlier comment](https://github.com/smartsdk/ngsi-timeseries-api/issues/256#issuecomment-537050315). If we're lucky, perhaps that's all we need to do.

If you'd like to give it a shot:

1. Update the Crate version in [deps.env](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/deps.env#L8)
2. Patch `on duplicate ...` [statement](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/translators/crate.py#L362) as explained earlier
3. Assuming you've got Python 3.6 on your box, cd to the repo root dir and run

    $ pip install pipenv
    $ pipenv install
    $ source setup_dev_env.sh
    $ sh run_tests.sh

If all hell breaks loose, well nice try, but let's leave it at that. On the other hand if there are no errors, you could build a new QL image

    $ docker build -t quantumleap .

deploy it to your cluster and hammer it away, trying as many queries as you can. This would be very valuable as it could unearth lots of issues that we could, in time, fix.

**Comment by c0c0n3** [comment]
Oh forgot to mention. A couple of tests will fail regardless, just ignore them---see #292.

**Comment by chicco785** [comment]
@pinkerltm as you can see i made an attempt in #300 probably not so painful to fix except if one of the test failing is actually a crate 4.x bug.
feel free to build an image from the branch and play with it

**Comment by chicco785** [comment]
@pinkerltm @tstorek 
except few last checks, we are ready with cratedb 4.0 support. it would be great if you could run few tests before we merge to master.
an image build is available as `smartsdk/ngsi-timeseries-api:fix-256`

**Comment by c0c0n3** [comment]
@pinkerltm @tstorek 
We just merged #300 into master with experimental Crate 4 support. By the time you read this the latest QL image with Crate 4 support should have become available on Docker Hub.

    docker pull smartsdk/quantumleap:latest

to get the goodies. It'd be great if you could take it for a spin and report any issues here on GitHub.
Many thanks!

**Comment by pinkerltm** [comment]
@c0c0n3 @chicco785 thanks a lot for your great effort...sorry I didn't recognize this as long as I received the issue closed per mail. I will test it immediately on our dev cluster.
