### ISSUE TITLE
Travis tests fail

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#269]
**Describe the bug**
It looks like #260 is coming back to haunt us :-o

**To Reproduce**
Look at Travis logs for #266, #268 

**Expected behavior**
Clean Travis test run.

**Environment (please complete the following information):**
 - Travis

**Additional context**
N/A

**Comment by chicco785** [comment]
i am not sure is that.

**Comment by c0c0n3** [comment]
well, um, do the errors on Travis look different than what you saw in #260? It looks like the build fails cos test code can't connect to QL. This is doubly weird though, since if you look at the Travis output for #271, `ens4` has an IP of `10.20.1.120` which is the same picked up by the test code. For example, the version test does a plain GET and looking at the Travis log (`address = ('10.20.1.120', 8668) ...`) the URL should be `http://10.20.1.120:8668/v2/version` which is correct? What the heck?

For the record, I've just managed to get a clean test run on my box using the latest in `master`, so it must be something on Travis I guess. I'll see if there's any "official" docs that say how to set up a docker network reliably on Travis.

**Comment by c0c0n3** [comment]
After digging deeper, it turns out the reason for the tests failing isn't that the test code can't see the Docker network. The actual problem is that the QL process inside the Docker container fails to start properly, so there's no server socket bound to port `8668`, hence the "connection refused" error we see in the logs.

What makes QL fail to start? In this build I've output the Docker logs:

https://travis-ci.org/smartsdk/ngsi-timeseries-api/builds/605998561?utm_source=github_status&utm_medium=notification

As you can see, when `connexion` tries to build the API from the Swagger spec, it indirectly causes the Reporter to import the Crate translator which in turn triggers the import of `utils.common` where we import `pytest`, but it looks like `pytest` is nowhere to be seen! This is puzzling since if you look at the Travis log, you can clearly see `pytest` being installed in the QL Docker image as it gets built.

Anyway, my conclusion at this stage is that we got bitten by **dependency hell**.

In fact, the Docker image build on Travis uses the latest `python:3.6-alpine` which is based on Alpine `3.10` as the Travis log gives away:

    fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz 

Also, after eyeballing the Travis log I could pick up some weirdness like `certifi` being installed as a dep of `pipenv` but then later on:

    Found existing installation: certifi 2019.9.11
        Uninstalling certifi-2019.9.11:
            Successfully uninstalled certifi-2019.9.11 

as we install the Python deps from `requirements.txt`. I've got a faint recollection of Tomas telling me how things went awry in the past when `connexion` tried to generate the API and the culprit seemed to be a particular `certifi` version---through one gazillion layers of indirection I guess. So this may be an avenue to explore.

Now for the fun part. All this works without a glitch on my box. Why, you may ask. Well, it turns out I have an older `python:3.6-alpine` cached in my local Docker repo and that's the one it gets used when I build the QL image. My `python:3.6-alpine` is based on Alpine `3.8`:

    $ docker image inspect python:3.6-alpine
    [{
        "Id": "sha256:1837080c5e87e105901a6c2c318adca4101dce8866e239cb9109704771503248",
        "RepoTags": [ "python:3.6-alpine"],
        "RepoDigests": [
            "python@sha256:4ae5142f052c4efd0bede8483f8ca43a73e8fcfce5dbf8f581967c2c9bac597b"
        ],
        ...
        "Created": "2018-12-26T09:18:19.779148668Z",
        ...
         "ContainerConfig": {
            ...
        "Env": [
                ...
                "PYTHON_VERSION=3.6.8",
                "PYTHON_PIP_VERSION=18.1"
            ],
        ...

And when building the QL image I can see this being output:

    fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz

So an easy way out would be to pin the `python:3.6-alpine` to the one using Alpine `3.8`  as in

    FROM python:3.6.8-alpine3.8

just like [those guys did](https://github.com/docker-library/python/issues/378). I'll give it a shot and see if it helps...
