### ISSUE TITLE
Follow up to PR #278

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#281]
Just a reminder of minor improvements we left out of PR #278.  If we can find the time for that, we could implement them as discussed there. As a bare minimum though we should update the test cases in `test_incomplete_entities.py` to take into account the changes introduced by PR #278---see discussion over there.

**Comment by c0c0n3** [comment]
Tests updated, see #282. I reckon we can actually ditch this issue now?

**Comment by daminichopra** [comment]
Hi @c0c0n3 , Please close this issue as [PR#282](https://github.com/smartsdk/ngsi-timeseries-api/pull/282) has been merged. Thank you :)

**Comment by c0c0n3** [comment]
hi @daminichopra, thanks for reminding me!
