### ISSUE TITLE
Sanity check GET /version returns 404 on Docker Image tagged :0.7.5 while working on :latest 

### ISSUE THREAD

**Issue by pinkerltm** [smartsdk/ngsi-timeseries-api#297]
I deployed smartsdk/quantumleap:0.7.5 on a kubernetes cluster but it did not pass the sanity check of a GET Request on localhost:8668/version as it always returned 404.

As I changed to tag smartsdk/quantumleap:latest, a sanity check returnes Status Code 200 and version number 0.7.5 in the content.

I also recognized, that both images are different in size.

**Comment by chicco785** [comment]
i believe /version works only for next release, 0.7.5 is still using /v2/version

**Comment by c0c0n3** [comment]
@pinkerltm thank you for trying Quantum Leap. @chicco785 is right. If you'd like to use the current stable release `0.7.5`, then the version endpoint is at `/v2/version`. On the other hand if you'd rather be on the bleeding edge and use the latest image on DockerHub, then the path is: `/version`. Further details in #274.

**Comment by chicco785** [comment]
@pinkerltm on another matter, this may be relevant to you: https://github.com/orchestracities/charts
