### ISSUE TITLE
move to uwsgi

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#301]
**Is your feature request related to a problem? Please describe.**
flask runner are not the recommended solution for production

**Describe the solution you'd like**
move to uwsgi, see here:
https://github.com/hellt/nginx-uwsgi-flask-alpine-docker/blob/master/python3/Dockerfile

**Additional context**
Hopefully this make ql container more performing

**Comment by c0c0n3** [comment]
See also Flask deployment options over here:

* https://flask.palletsprojects.com/en/1.1.x/deploying/#deployment

Notice what the docs say about using the built-in server for prod workloads

> Flask’s built-in server is not suitable for production

oh dear :-)

**Comment by chicco785** [comment]
you get the exact same message everytime quantumleap starts...

**Comment by c0c0n3** [comment]
In the end we decided to use Gunicorn instead of uWSGI. Since we now have implemented the necessary Gunicorn plumbing (#357), I'm closing this issue.
