### ISSUE TITLE
Make MAX limit for retrieved rows an env variable

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#303]
**Is your feature request related to a problem? Please describe.**

Currently the  MAX limit is hardcoded

**Describe the solution you'd like**

I would like it to be a ENV variable i can change.

**Comment by c0c0n3** [comment]
We should also update the spec accordingly to state that the max can be configured and advise against setting it too low as a low max would make more likely the below issues detailed in [The Mother of all Queries][moaq] section of the [wiki][wiki]:

* [Hidden partial results][partial-res]
* [Limit not honoured][lim-not-honoured]



[wiki]: https://github.com/smartsdk/ngsi-timeseries-api/wiki
[moaq]: https://github.com/smartsdk/ngsi-timeseries-api/wiki/The-Mother-of-all-Queries
[partial-res]: https://github.com/smartsdk/ngsi-timeseries-api/wiki/Issues#hidden-partial-results
[lim-not-honoured]: https://github.com/smartsdk/ngsi-timeseries-api/wiki/Issues#limit-not-honoured

**Comment by daminichopra** [comment]
Hi @c0c0n3 , Please assign this issue to me if no one is working on it. Thank you

**Comment by c0c0n3** [comment]
Hi @daminichopra, assigned to you. thanks for offering :-)

**Comment by c0c0n3** [comment]
closed by #330
