### ISSUE TITLE
Reduce code duplicates

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#314]
**Is your feature request related to a problem? Please describe.**
Large part of codes are duplicated between Crate and Timescale.

**Describe the solution you'd like**
Reduce duplication to improve maintainability.

**Comment by c0c0n3** [comment]
Guilty as charged, see TODO I left [here](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/translators/timescale.py#L13) when I implemented initial support for Timescale---we had no time for proper design and refactoring then. Thanks for reminding me.

There's also lots of similar code in most of the reporter modules that deal with queries, scars of past C&P technology.

**Comment by chicco785** [comment]
No worries :) In my free time at night if kids wake me up, in the attempt to learn basis of python, I will make a proposal, and then share with you for revision and consolidation.

**Comment by c0c0n3** [comment]
closed by #315
