### ISSUE TITLE
store raw json incoming notification

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#318]
**Is your feature request related to a problem? Please describe.**
To improve management of incoming data and provide later support to recover badly formatted data not mapping to columns, it would be nice to store raw json data.

**Describe the solution you'd like**
have a "_raw" column for each data entry in the entity column where we can store source json data. this column should be stored also in case the normal injection fails

**Describe alternatives you've considered**
have a separate table where raw json data are stored.

**Comment by c0c0n3** [comment]
closed by #335
