### ISSUE TITLE
API selective on content field 'source'

### ISSUE THREAD

**Issue by pinkerltm** [smartsdk/ngsi-timeseries-api#323]
We are using the [Device](https://swagger.lab.fiware.org/?url=https://raw.githubusercontent.com/smart-data-models/dataModel.Device/master/Device/swagger.yaml)-"smart-data-model" on our Context Broker which get persisted to CrateDB by QuantumLeap. First we fired a couple of testrequests to Context Broker, where the field 'source' of the datamodel got the value 'application/test-data', which led to the creation of the table schema by quantum leap and the first couple of datasets.

Afterwards we imported real history data which we already got as CSV. The entity_ids of the devices are certainly the same and there is also overlap (entity_id, time_index), but the source is now 'evn/devices-csv' 

When I query the QL API for all datasets of an entity where both sources exists for a certain timespan (fromDate and toDate) only the datasets of the testdata source type are delivered. When I delete the old datasets from the table, nothing gets delivered by the API. It looks like the imported datasets do not exist for quantum leap, but they are actually in the database.

Is there some kind of index which got corrupted by importing the same entities from a different source? I already checked if the entry in `md_ets_metadata` doesn't fit the datasets in any way, but schema and types are equivalent to the types used in the database.

**Comment by chicco785** [comment]
@pinkerltm i am not sure i understand what happens. how did you import the cvs data?
in principle, there should not be any issue (at least on quantumleap side). one thing though you have to keep in mind is that when you import lot of data in a batch way to crate, it takes some times for the data to be "consolidated" and hence available in queries.

said so, to investigate your problem, we need to be able to reproduce it. thus, can you provide a minimal set of scripts and instructions to reproduce it?

**Comment by pinkerltm** [comment]
the problem doesn't have anything to do with the "source" field, therefore closing this
