### ISSUE TITLE
QL doesn't notify when CrateDB is locked due to less available memory

### ISSUE THREAD

**Issue by ccsr** [smartsdk/ngsi-timeseries-api#334]
When the allocated available memory to CrateDB goes below 15%, CrateDB gets locked and QL doesn't give any errors.

1. Create a subscription from Context Borker to QL and wait till the allocated free disk is below 15%
2. CrateDB locks and QL don't give any errors

**Expected behavior**
QL should return "not processed or not updated" error code to subscription call

**Comment by chicco785** [comment]
@ccsr thx, we will check

**Comment by daminichopra** [comment]
Hi @chicco785 @ccsr @c0c0n3 , I investigated on this issue and below are the error logs which i get while notifying request.

![Capture](https://user-images.githubusercontent.com/35693908/88383492-400d7b00-cdc8-11ea-9019-de9b70194d91.PNG)
![capture1](https://user-images.githubusercontent.com/35693908/88383501-44d22f00-cdc8-11ea-8f88-e66eb44cc0b0.PNG)

Please confirm and assign this issue to me if nobody is working on this Issue. Thank you :)

**Comment by chicco785** [comment]
@daminichopra assigned!

**Comment by c0c0n3** [comment]
closed by #346
