### ISSUE TITLE
INSERT...ON DUPLICATE DO ...  Behaviour

### ISSUE THREAD

**Issue by pinkerltm** [smartsdk/ngsi-timeseries-api#336]
Because Crate sometimes gets locked and therefore misses CB notifications we are facing uncomplete timeseries data where we tend to fill up the gaps later on. Fortunately we collect data not only via Context Broker but also in other stores so we are able to just "replay" certain timespans. 

Doing this we risk to sometimes produce duplicates which we also have to tidy up afterwards.

The better solution for me would be to set up an unique Index/primary key on `entity_id`, `time_index` and `value` so that QunatumLeap could use `...ON DUPLICATE DO NOTHING`. Duplicates wouldn't arise anytime then.

**Comment by chicco785** [comment]
hi @pinkerltm 

* as you know we have a value for each attribute, so adding the ON DUPLICATE DO NOTHING would basically means convert into key every column, which i suspect is performance killing. This is not really performing. Not also how this is compatible with CRATEDB SQL in v4 (which seems to not support on DUPLICATE KEY): https://crate.io/docs/crate/reference/en/4.1/sql/statements/insert.html
* other people may prefer to replace duplicate data (and i would consider as key `entity_id`, `time_index`, `fiware_servicepath`), so here the logic starts to become quite complex.
* what is more concerning to us are notifications that get lost because of cratedb. while this may happen because of bad formatting, this should not be the case, unless crate has not enough resources.

**Comment by pinkerltm** [comment]
Sorry you are right, its INSERT ... ON CONFLICT ... now https://crate.io/docs/crate/reference/en/latest/sql/statements/insert.html

To include `value` in the key seems odd in the first place, according to NGSI SmartDataModels its allowed to (url)encode multiple measures into a Text Value. So in our IoT environment we get update messages which update a single measurement, and we have to translate them so that Context Broker Updates the urlencoded Text value (only one of multiple measurements in there). Doing that it is (not likely but) possible, that the same entity got two or more updates at the very same time_index. We have to distinguish these, therefore value would be part of the key. Thanks for clarification, yes fiware_servicepath should certainly also be part of the index.

Nevertheless I have to admit, the logic would become complex. I am not really sure about a better way to tackle this other to frequently tidy this mess up with batch jobs afterwards.

Crate is deployed in Azure Kubernetes Service with 3 Nodes, 2 CPUs and 2GB Heap each. Although it doesn't hit any ressource pressure we will move onto a much larger cluster and give crate a lot more ressources as it seems that it is mostly failing when there are very high traffic peaks. We use Erlang in our backend to gather Sensor data. This is transformed to NGSI and posted to 3 Orions which rely on a HA Mongo Deployment and notify a HA QuantumLeap Deployment (everything couples of 3). All this is running on a rather small 5 Node AKS Cluster. I am really interested in how to setup all this to get a really reliable data pipeline.

**Comment by chicco785** [comment]
are you aware of this: https://github.com/orchestracities/charts ? may help, and if you want to contribute updates, you are of course welcome.

i feel your pain for the device model. i consider it actually it wrong. which is the reason why, we don't store "value", but only actual device info and then lift "values" to a specific model e.g. AirQuality.

regarding the feature request, to be honest, it is not a priority for us. as usual, you may pick it up and try something, or alternatively, if this is really important and urgent, we can custom develop.

**Comment by pinkerltm** [comment]
@chicco785 oh thats really nice! although I prefer Operators over Helm Charts wherever there are some available (can't manage writing golang also for now). We put most of these together on our own (Simple Crate STatefulSet Deployment without any lifecycle management). THANKS!

And yes, we also came to the conclusion that the Device Model is simply wrong in this case and propose to introduce an DeviceObservation as an extension to store multiple measurements of a single Device (there aren't very much specific datamodels for energy). Thats pretty much the same what the Sensor Observations and Measurements Standard says and what OGC SensorThings has implemented.

regarding the feature request: don't worry, I am aware that this is indeed very special. But perhaps there is someone else who also wants to have more control about how things get persisted actually.

**Comment by chicco785** [comment]
we combine charts with flux: https://fluxcd.io/

**Comment by chicco785** [comment]
it basically provide a generic operator for helm charts configurations, that you can version in git, and it keeps in synch the config in git and the cluster

**Comment by pinkerltm** [comment]
When it deploys YAML, it also deploys Operators.....nice one. Perhaps something we can use for our new nightly-dev cluster

**Comment by pinkerltm** [comment]
I think I will close this now, as we are more and more missing the topic.... nevertheless I found it nice to exchange experiences on clustering FiWare properly. Perhaps there is a better platform for this (Slack, RocketChat, SE, Reddit, ...)?
