### ISSUE TITLE
New milliseconds in Creation date and modification date break fromDate and toDate

### ISSUE THREAD

**Issue by gboege** [smartsdk/ngsi-timeseries-api#337]
**Describe the bug**
In the latest updates to ContextBroker there seem to be additions of milliseconds to the creation date and modification date. See this link and the picture attached:
![Milliseconds](https://user-images.githubusercontent.com/44926950/87218885-3c550f80-c357-11ea-8972-21d20bb67edb.png)
https://github.com/telefonicaid/fiware-orion/blob/c3b30bd940b88d1b9654553fc9b62cd01cd0e468/test/functionalTest/cases/2632_timezones/timezones.test

**To Reproduce**

Using the latest orion docker images without a version number (image: fiware/orion) seems to already bring this feature. This breaks the query filters: fromDate and toDate. It simply ALWAYS delivers a 404, no entities found. 
Doing a subscription with metadata in the notification:     "metadata": ["dateCreated", "dateModified"],

curl "http://localhost:8668/v2/types/testtype/attrs/testattribute?fromDate=2018-07-01T00:00:00&toDate=2022-07-06T00:00:00" \
     -H 'Fiware-Service: service' \
     -H 'Fiware-ServicePath: /'

**Expected behavior**
Entities that were available without the filter do not show up with the filter, even if the time range is correct.

**Environment (please complete the following information):**

**Additional context**
Looks like there is some kind of mismatch of datatypes... before milliseconds and after.

Just setting down the context broker image to 2.3.0 did the trick with the exact same queries.

**Comment by chicco785** [comment]
which version of the image are you using?

**Comment by gboege** [comment]
It is only 4 days old... 

https://github.com/telefonicaid/fiware-orion/blob/c3b30bd940b88d1b9654553fc9b62cd01cd0e468/CHANGES_NEXT_RELEASE

And there is only the "latest" images updated so far. No image with a version Number. It will be part of the next release, but without naming a specific version you have it already today.
https://hub.docker.com/r/fiware/orion/tags?page=1

**Comment by gboege** [comment]
see creDate and modDate
https://github.com/telefonicaid/fiware-orion/blob/c3b30bd940b88d1b9654553fc9b62cd01cd0e468/doc/manuals/admin/database_model.md

**Comment by chicco785** [comment]
sorry, my question was not clear :) which version of quantumleap image ?

**Comment by gboege** [comment]
this is my demo docker-compose ... changed to orion 2.4.0 ... now it works smoothly

version: "3.7"

services:

  orion:
    restart: always
    image: fiware/orion:2.4.0
    hostname: orion
    container_name: orion
    networks:
      - main
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    command: -dbhost mongo-db -logLevel DEBUG

  mongo-db:
    restart: always
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    networks:
      - main
    ports:
      - "27017:27017"
    volumes:
      - vol-mongo-db:/data
    command: --bind_ip_all --smallfiles

  crate-db:
    restart: always
    image: crate:3.1.2
    hostname: crate-db
    container_name: crate-db
    networks:
        - main
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
    volumes:
      - vol-crate-db:/data
    command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"

  quantum-leap:
    restart: always
    image: smartsdk/quantumleap:0.7.5
    hostname: quantum-leap
    container_name: quantum-leap
    networks:
        - main
    ports:
      - "8668:8668"
    depends_on:
      - crate-db
    environment:
      - CRATE_HOST=crate-db
      - CRATE_PORT=4200
      - QL_DEFAULT_DB=crate
      - DEFAULT_LIMIT=1000
      - USE_GEOCODING=False
      - LOGLEVEL=INFO


networks:
  main:

volumes:
  vol-mongo-db:
  vol-crate-db:
  vol-grafana:

**Comment by chicco785** [comment]
would you mind testing with smartsdk/quantumleap:latest? is the dev version and we made few updates to date management, maybe it solves already

**Comment by gboege** [comment]
Just tested. And no:
In 4 combinations:

CB = Image Version Context Broker
QL = Image Version Quantum Leap

CB: 2.4.0
QL: 0.7.5
NO-404: /v2/
NO-404: /v2/entities
OK-200: /v2/entities/User-UUID-11
NO-501: /v2/attrs
NO-500: /v2/attrs/userDistanceKM-ALL
NO-404: /v2/types
NO-500: /v2/types/RideShareActivity
OK-200: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL
OK-200: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL + aggrMethod + aggrPeriod + fromDate + toDate


CB: latest
QL: 0.7.5
No-404: /v2/
NO-404: /v2/entities
OK-200: /v2/entities/User-UUID-11
NO-501: /v2/attrs
NO-500: /v2/attrs/userDistanceKM-ALL
NO-404: /v2/types
NO-500: /v2/types/RideShareActivity
OK-200: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL
OK-200: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL + aggrMethod + aggrPeriod + fromDate + toDate


CB: 2.4.0
QL: latest
QL: 0.7.5
OK-200: /v2/
OK-200: /v2/entities
OK-200: /v2/entities/User-UUID-11
OK-200: /v2/attrs
OK-200: /v2/attrs/userDistanceKM-ALL
NO-404: /v2/types
OK-200: /v2/types/RideShareActivity
OK-200: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL
NO-404: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL + aggrMethod + aggrPeriod + fromDate + toDate

CB: latest
QL: latest
QL: 0.7.5
OK-200: /v2/
OK-200: /v2/entities
OK-200: /v2/entities/User-UUID-11
OK-200: /v2/attrs
OK-200: /v2/attrs/userDistanceKM-ALL
NO-404: /v2/types
OK-200: /v2/types/RideShareActivity
OK-200: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL
NO-404: /v2/types/RideShareActivity/attrs/userDistanceKM-ALL + aggrMethod + aggrPeriod + fromDate + toDate


There are error codes in all combinations. At least in my tests. 

And no, in my tests, the new floating point dates seem not to be covered.

**Comment by chicco785** [comment]
@gboege thx, we are looking into this

**Comment by chicco785** [comment]
@gboege following investigations, the issue is related to the usage of crate 3.x and fixed in #371, we back ported the fix to 0.7.6 as well.

* /v2/types without entityType is not a valid api call

so in 0.7.6 and latest the actual issue in your calls is related to:
* /v2/types/RideShareActivity/attrs/userDistanceKM-ALL + aggrMethod + aggrPeriod + fromDate + toDate

using crate 4.x would not have triggered the issue as reported in #371 

regarding 0.7.5, as by reply (i suspect), the following apis where yet not implemented:
* /v2/
* /v2/entities
* /v2/attrs
* /v2/attrs/{}
* /v2/types/{}

**Comment by chicco785** [comment]
@Siedlerchr in #371 confirmed that the issue related to `fromDate` and `toDate` with crate 3.x is solved. @gboege can we close?

**Comment by gboege** [comment]
sure. let's close it.
