### ISSUE TITLE
improve logs

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#342]
> INFO:reporter.reporter:Notification successfully processed

list entity ids, tenant, and servicePaths

> INFO:geocoding.factory:Env variable USE_GEOCODING set to 'true', using this value.
> INFO:geocoding.factory:Env variable REDIS_HOST set to 'redis-redis-ha', using this value.
> INFO:geocoding.factory:Env variable USE_GEOCODING set to 'true', using this value.
> INFO:geocoding.factory:Env variable REDIS_HOST set to 'redis-redis-ha', using this value.
> INFO:geocoding.factory:Geo Cache env variables set, building a cache.
> INFO:geocoding.factory:Env variable REDIS_HOST set to 'redis-redis-ha', using this value.
> INFO:geocoding.factory:Env variable REDIS_PORT not set, using default value of: 6379
> INFO:reporter.reporter:Env variable LOGLEVEL not set, using default value of: INFO
> INFO:translators.factory:Env variable QL_DEFAULT_DB not set, using default value of: crate
> INFO:translators.factory:Backend selected for tenant 'ekz' is: crate

move to debug

> WARNING:translators.crate:'string' is not a supported NGSI type. Please use any of the following: Array, Boolean, ISO8601, DateTime, Integer, geo:json, geo:point, Number, Text, StructuredValue, timeindex. Falling back to Text.

List entityId and attribute

**Comment by daminichopra** [comment]
Hi @chicco785 , Please assign this issue to me if no one is working on it.

Also i want to confirm my understanding on this:

1.  Need to  include list `entity ids, tenant, and servicePaths` with `Backend selected for tenant 'ekz' is: crate`.
2.  `INFO` needs to be moved to `DEBUG`
3.  Need to include List `entityId and attribute`  with `WARNING:translators.crate:'string' is not a supported NGSI type. Please use any of the following: Array, Boolean, ISO8601, DateTime, Integer, geo:json, geo:point, Number, Text, StructuredValue, timeindex. Falling back to Text.`
4. `WARNING` needs to be moved to `DEBUG`.

Please confirm the understanding. Thank you

**Comment by chicco785** [comment]
> Hi @chicco785 , Please assign this issue to me if no one is working on it.
> 
> Also i want to confirm my understanding on this:
> 
> 1. Need to  include list `entity ids, tenant, and servicePaths` with `INFO:reporter.reporter:Notification successfully processed`

correct

> 2. `INFO` needs to be moved to `DEBUG`

geocoding.factory:Env
geocoding.factory:Geo
translators.factory:Backend 

should be `DEBUG`


> 3. Need to include List `entityId and attribute`  with `WARNING:translators.crate:'string' is not a supported NGSI type. Please use any of the following: Array, Boolean, ISO8601, DateTime, Integer, geo:json, geo:point, Number, Text, StructuredValue, timeindex. Falling back to Text.`

This warning tells that one of the attributes provided is not in the proper format,
the warning needs to include the entityId where this occurred and the attribute that caused the error.

> 4. `WARNING` needs to be moved to `DEBUG`.

No, it's ok to stay `WARNING`

> 
> Please confirm the understanding. Thank you

**Comment by c0c0n3** [comment]
closed by #355
