### ISSUE TITLE
Programmatic deletion of Table from Crate DB 

### ISSUE THREAD

**Issue by ilarimikkonen** [smartsdk/ngsi-timeseries-api#347]
**Is your feature request related to a problem? Please describe.**
When data is received by QL via notifications from CB, a table is created to Crate DB. Data can be deleted from Crate via API endpoints, but the table stays in the Crate DB. 

**Describe the solution you'd like**
An API endpoint to remove table from the Crate DB

**Describe alternatives you've considered**
1) exec to container 2) start Crash 3) DROP TABLE
This is not convinient for some use cases, API endpoint would be good for programmatic access.

**Additional context**
Over time, tables can accumulate to the Crate DB and this new API endpoint would help with house keeping.

**Comment by c0c0n3** [comment]
> Data can be deleted from Crate via API endpoints, but the table stays in the Crate DB.

If you delete **all** records through the API delete endpoint, then this should happen automatically:

1. The entity table gets dropped---i.e. QL should issue the `DROP TABLE ...` statement for you.
2. The corresponding table entry should be deleted from the metadata table.

It looks like this isn't happening for you? Can you confirm you deleted **all** the records in the table **using the delete API**? Thanks!

**Comment by ilarimikkonen** [comment]
Setup:
Running Crate 3.3.5. with 0.7.5. QL. Orion in front

Test:
1) create a new tenant: deletetest1 - OK
2) push data to tenant - OK
3) get data from tenant - OK
4) create a subscription to QL - OK
5) push data - OK
6) check subscription - OK
7) check data from Crate - OK:
```
cr> select * from  "mtdeletetest1"."etdeletetest";
+------------+-------------+--------------------+---------------+-------+
| entity_id  | entity_type | fiware_servicepath |    time_index | value |
+------------+-------------+--------------------+---------------+-------+
| deletetest | deletetest  | /                  | 1597135006000 |   1.0 |
| deletetest | deletetest  | /                  | 1597135138000 |   2.0 |
+------------+-------------+--------------------+---------------+-------+
SELECT 2 rows in set (0.006 sec)
cr>
```
8) do delete - OK:
```
curl --location --request DELETE 'https://sthdata.testurlhere/ql/v2/types/deletetest' \
--header 'fiware-servicepath: /' \
--header 'fiware-service: deletetest1' 
```
9) check from crate - NOK:
```
cr> select * from  "mtdeletetest1"."etdeletetest";
+-----------+-------------+--------------------+------------+-------+
| entity_id | entity_type | fiware_servicepath | time_index | value |
+-----------+-------------+--------------------+------------+-------+
+-----------+-------------+--------------------+------------+-------+
SELECT 0 rows in set (0.006 sec)
cr>
```

RESULT: - table remains
EXPECTED: - table is dropped

**Comment by ilarimikkonen** [comment]
hang on.. I may have confused concepts of schema and table. I'll check again.

**Comment by ilarimikkonen** [comment]
I think the (potential) problem scenario is as such: 1) table is dropped. 2) someone creates a new tenant with the same name and type, but pushes different data. Then because the entry is persisted in the md_ets_metadata table there is an error.  Given that same data types would be used, this is no problem, but there is no guarantee. 
But I need to test and validate this.

**Comment by ilarimikkonen** [comment]
Retested: schema and table remain after deleting data using `/V2/types` endpoint. entry stays in md_ets_metadata. no data in table.
If I do a drop table: `cr> drop table  "mtdeletetest3"."etdeletetestduno";` schema and table entries are removed and entry stays in md_ets_metadata

**Comment by chicco785** [comment]
@ilarimikkonen thx for the scouting. we look into extending https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/reporter/tests/test_delete.py to be sure the test you mention is covered and hence implemented.

**Comment by chicco785** [comment]
fyi: code that cover that is there, but clearly is not executed as expected (see https://github.com/smartsdk/ngsi-timeseries-api/blob/master/src/translators/sql_translator.py#L985)

**Comment by chicco785** [comment]
@ilarimikkonen we checked the test and verified database behaviour (which is not automatically verified in the test).

it seems everything looks fine:
1. data is deleted.
2. table is deleted.
3. metadata are deleted.

can you provide a small script to reproduce your test? that would help to understand what goes wrong and why 

thx

**Comment by ilarimikkonen** [comment]
IDK how to help here; assuming that there is already some data in the database, doing a curl like this does the deletion, but leaves some artifacts like mentioned:

`curl --location --request DELETE 'https://sthdata.domain.fi/ql/v2/types/tenanttests' \
--header 'fiware-service: bbbbb' \
--header 'fiware-servicepath: /'`

I've been trying to figure out a script, but this is not a trivial effort for me. @chicco785 can we organise an online session where I demo the issue?

**Comment by ilarimikkonen** [comment]
```
curl --location --request POST 'https://URL/ql/v2/notify' \
--header 'fiware-service: bbbbb' \
--header 'fiware-servicepath: /' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer TOKEN' \
--data-raw '{
    "subscriptionId": "ID_FROM_SUB",
    "data": [{
	"id": "un3",
	"type": "deletetestDuno",
	"batteryVoltage": {
		"type": "Text",
		"value": "ilariso"
	}
	}]
}'

curl --location --request DELETE 'https://URL/ql/v2/types/deletetestDuno' \
--header 'fiware-service: bbbbb' \
--header 'Authorization: Bearer TOKEN' \
--header 'fiware-servicepath: /'
```
Result in crate:
```
cr> select * from "mtbbbbb"."etdeletetestduno";
+----------------+-----------+-------------+--------------------+------------+
| batteryvoltage | entity_id | entity_type | fiware_servicepath | time_index |
+----------------+-----------+-------------+--------------------+------------+
+----------------+-----------+-------------+--------------------+------------+
SELECT 0 rows in set (0.006 sec)
cr>
```
and metadata and schema remain. @chicco785 is this enough? if not, let's have a call.

**Comment by c0c0n3** [comment]
@ilarimikkonen thank you so much for this. We'll try to reproduce and add this test case to the test suite as @chicco785 mentioned some time ago. We'll keep you posted :-)

**Comment by chicco785** [comment]
thx @ilarimikkonen there is indeed a bug, tests have always no servicePath, so this case was not covered.

**Comment by c0c0n3** [comment]
@ilarimikkonen we just merged #365 into master with a fix for your issue. We also changed slightly the delete endpoint so that it won't drop tables by default---to avoid some race conditions, see #365 about it. To drop the table you'll have to explicitly add a query parameter `dropTable=true` to the URL you'd normally use to delete entities by type as in

    curl -X DELETE /v2/types/doomedDevice?dropTable=true

The above will delete all entity data for `doomedDevice`, drop the `etdoomeddevice` table, and remove the corresponding entry from the metadata table. Notice `dropTable` should only be used for maintenance after the devices whose data is written to the table are decommissioned and no further writes are possible. In fact, race conditions are possible if entities of that type are POSTed to the notify endpoint while the underlying clean-up procedure is in progress.

**Comment by ilarimikkonen** [comment]
sweet @c0c0n3 ! When do you think this will make it's way to a release?

**Comment by c0c0n3** [comment]
hi @ilarimikkonen, we're working on getting the Timescale backend on par with Crate which is possibly the last task before releasing `0.8`. If everything goes well, we should be able to release `0.8` towards the end of next week or the week after that. `0.8` will include this fix as well as a fully-fledged Timescale backend and Gunicorn support.
