### ISSUE TITLE
Log entry timestamps

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#348]
**Is your feature request related to a problem? Please describe.**
Currently log entries don't have a timestamp, e.g.

    DEBUG:crate.client.http:Sending request to /_sql? ...
    INFO:reporter.reporter:Notification successfully processed

**Describe the solution you'd like**
Prepend log entries with a timestamp, e.g.

    [2020-07-15 10:41:41.568+00] DEBUG:crate.client.http:Sending request to /_sql? ...
    [2020-07-15 10:41:42.102+00] INFO:reporter.reporter:Notification successfully processed

**Describe alternatives you've considered**
N/A

**Additional context**
Have a look at QL logs.

**Comment by daminichopra** [comment]
Hi @chicco785 @c0c0n3 , I would like to work on this Issue. Please assign. Thank you

**Comment by c0c0n3** [comment]
closed by #352
