### ISSUE TITLE
Add PID and TID to log lines

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#356]
### Is your feature request related to a problem? Please describe
We're in the process of switching from the Flask dev server to Gunicorn. There'll be lots of processes kicking around and, depending on Gunicorn worker type, async IO or/and multiple threads per process all of which is going to make it really hard to tell which log lines belong to which execution flow.

### Describe the solution you'd like
Add process ID and thread ID to the log line. We might need more info than that to reconstruct single flows, but at least PID and TID give us a fighting chance.

### Describe alternatives you've considered
N/A

### Additional context
See [this comment](https://github.com/smartsdk/ngsi-timeseries-api/pull/355#issuecomment-688280568) to #355.

**Comment by daminichopra** [comment]
Please assign this issue to me. Thanks

**Comment by c0c0n3** [comment]
no prob, done, thx!

**Comment by c0c0n3** [comment]
closed by #367.
