### ISSUE TITLE
Support arrays of different types

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#36]
NGSI mentions an Array type, it seems it could be of anything, but need to better investigate.

But Crate's arrays have types: https://crate.io/docs/crate/reference/en/latest/appendix/data-types.html#array

**Comment by chicco785** [comment]
I think Orion used the StructuredValue representation, exactly to simplify the type management inside arrays. Thus, that could be a good option also for QL.

**Comment by taliaga** [comment]
Duplicated of / Covered by #147
