### ISSUE TITLE
Gunicorn container halts test session

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#362]
### Describe the bug
During the test session in the Travis build, it looks like the Gunicorn server in the Docker container suddenly comes to the foreground, so tests stop, and eventually Travis kills the build.

### To Reproduce
Do a clean check out of the `master` branch, **fully** prune your Docker system taking care of not leaving behind any dangling images/containers, remove all your Python venvs, clean up any Python env vars, then in a fresh terminal:

    $ cd where/you/cloned/ngsi-timeseries-api
    $ pipenv install
    $ source setup_dev_env.sh
    $ sh run_tests.sh 

At some point during the test session you should see the Gunicorn container coming to the foreground and making the tests hang.

### Expected behavior
Gunicorn container should sit in the background, allowing `pytest` to go on with the test session.

### Additional context
See any of the following build logs:

- https://travis-ci.org/github/smartsdk/ngsi-timeseries-api/builds/727051434
- https://travis-ci.org/github/smartsdk/ngsi-timeseries-api/builds/726970500

**Comment by chicco785** [comment]
the problem is not gunicorn, but the new image using entrypoint instead of command, which makes the integration tests fail in the content load fase

**Comment by c0c0n3** [comment]
ah, thanks for that. I wonder why tests were passing for a while even on Travis as well as on our boxes. Anyhoo, let's fix forward.

**Comment by c0c0n3** [comment]
fixed by #363
