### ISSUE TITLE
Error k8s container

### ISSUE THREAD

**Issue by joselopezfernandez** [smartsdk/ngsi-timeseries-api#366]
My k8s cluster version is 1.17.7, everything was working but Azure told me to update and now quantumleap to cratedb doesn't work. I have this error in the pod:

OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

I have correct values in url /v2, like this, but no repsonse in entities, subscriptions:
{
  "attributes_url": "/v2/attrs",
  "entities_url": "/v2/entities",
  "notify_url": "/v2/notify",
  "subscriptions_url": "/v2/subscriptions",
  "types_url": "/v2/types"
}
But error 404 in url /v2/version.

Error 500 in url v2/entities.

This error in url /v2/attrs:
"Something went wrong with QL. Error: invalid literal for int() with base 10: 'tcp://10.0.202.21:4200'"

Please, I have to justify the project, I thank you if you can help me, to test the error, to track it, any ideas.
Thank you so much
Jose

**Comment by chicco785** [comment]
@joselopezfernandez so everything was working before the k8s update.... and now it is not, this weird.
my only guess is that by updating (are you using :latest ?) you updated your version of quantumleap to "latest" which does not have /v2/version path indeed and may need some more configuration parameters. (Never use as default image "latest" in prod it is not semantically versioned!!!)
If that's not the case, I am afraid it is really hard to say what's wrong.

I am afraid that information you provide is not detailed enough to say more than this.

**Comment by joselopezfernandez** [comment]
> so everything was working before the k8s update.... and now it is not, this weird.
> my only guess is that by updating (are you using :latest ?) you updated your version of quantumleap to "latest" which does not have /v2/version path indeed and may need some more configuration parameters. (Never use as default image "latest" in prod it is not semantically versioned!!!)
> If that's not the case, I am afraid it is really hard to say what's wrong.
> 
> I am afraid that information you provide is not detailed enough to say more than this.

Thanks @chicco785, I have tried using a previous version without success, it is easy to change, do you think that could be the error?

Do you know if there is a log file that I could check? Or the status of the service?
Regards.
Jose

**Comment by chicco785** [comment]
surely, there is ql log you can check, and see what's wrong

**Comment by chicco785** [comment]
the endpoint for health checks on the last version is "/health"

**Comment by joselopezfernandez** [comment]
I have the same http 404 error in v2/health

I have accessed the tests directory of the container, and I try to execute the file and it gives me an error,
/bin/sh: ./test_integration.py: Permission denied

The directory has these files:
__init__.py          common.py            docker-compose.yml   notify-load-test.js  run_load_tests.sh    run_tests.sh         test_bc.py           test_integration.py

**Comment by chicco785** [comment]
clearly your image is "latest"

v2/health was moved to /health since 0.7.5 or 0.7.6. (as for /version)

did you try to open quantum leap logs? did you set them in debug mode?

tests works if you configure them properly. regardless, your error may mean that you have some restrictions on uid or whatever other security aspect forced by k8s.

**Comment by joselopezfernandez** [comment]
Thanks @chicco785 , in /health I have the error:
{
  "details": {
    "crateDB": "cannot reach crate"
  },
  "status": "fail"
}

Sorry, I don't know how to see QL logs

**Comment by chicco785** [comment]
Kubectl logs-f qlpodname

So ql cannot reach crate, that’s your problem

**Comment by joselopezfernandez** [comment]
Hi @chicco785, everything works again, as you intuited from the beginning, it was a failure with latest version in my configuration. Going back to 0.7.0 it works as before.

Thanks for your time.
