### ISSUE TITLE
Rework Timescale Reporter tests

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#378]
This is just a reminder about tech debt from #374. The Reporter tests still need some love. At the moment there's a separate test suite for Timescale, but we could just have one test suite by adding Timescale to the existing Docker compose file and then route query tests to either backend using the existing service argument. This works for the query tests, for these other tests below we'll have to decide what to do:
  - `test_geo*` (only equality test): see #376 about it.
  - `test_health`: see #377 about it.
  - `test_integration`: works with Crate, possibly not needed for Timescale.
  - `test_multitenancy`: ditto.
  - `test_notify`: `test_no_value_no_type_for_attributes` is broken but it looks like the test was wrong to start with. In fact, the test checks (among other things) that a numeric attribute (temperature) with a string value (`'25'`) is inserted in Crate with a text column type. See #375 about it.
  - `test_sql_injection`: needs some massaging to make it work with Timescale too.
  - `test_subscribe`: ditto.
  - `test_time_format`: in principle these tests should be able to work with both backends but during test setup we connect to Crate.

**Comment by chicco785** [comment]
#403 should fix all issues but:
* `test_geo*` (only equality test): see #376 about it.
* `test_health`: see #377 about it.

**Comment by c0c0n3** [comment]
@chicco785 I'm closing this issue since like you said your PR fixed basically everything and for the rest we already have issues to remind us what to do.
