### ISSUE TITLE
docker container -" smartsdk/quantumleap " running in unhealthy state

### ISSUE THREAD

**Issue by mrproject06** [smartsdk/ngsi-timeseries-api#379]
Docker container of image-  smartsdk/quantumleap latest tag is running in unhealthy state. Source of image : https://hub.docker.com/r/smartsdk/quantumleap

**Comment by chicco785** [comment]
@mrproject06 can you:

1. provide your configuration?
2. report the outcome of curl -v http://qlhost:qlport/health
