### ISSUE TITLE
Attribute text fallback is broken

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#382]
### Describe the bug
On receiving a notification with an entity having an attribute of unknown type, QuantumLeap fails to save the value's attribute as text.

### To Reproduce

```
curl -v -X POST localhost:8668/v2/notify \
     -H 'Content-Type: application/json' \
     -d '
{
  "data": [
    {
       "id": "urn:ngsi-ld:Test:0002",
       "type": "Test",
       "errorNumber": {
         "type": "Integer",
         "value": 2
       },
       "refVacuumPump": {
         "type": "Relationship",
         "value": "urn:ngsi-ld:VacuumPump:FlexEdgePump"
       },
       "refOutgoingPallet": {
         "type": "Array",
         "value": [
           "urn:ngsi-ld:Pallet:0003",
           "urn:ngsi-ld:Pallet:0004"
         ]
       }
    }
  ]
}'
```

results in the following being stored in Crate

    errorNumber: 2
    refVacuumPump: null
    refOutgoingPallet: [ "urn:ngsi-ld:Pallet:0003", "urn:ngsi-ld:Pallet:0004" ]

### Expected behavior
The `refVacuumPump` value should be stored alongside the other attributes.

### Environment
The bug was observed both in QuantumLeap `0.7.6` and `master` with a Crate `4.1.4` backend.

**Comment by daminichopra** [comment]
Hi @c0c0n3 , Please assign this issue to me. Thank you

**Comment by chicco785** [comment]
this should be fixed by #373

**Comment by daminichopra** [comment]
Hi @c0c0n3 @chicco785 , I have fixed this issue. Shall i raise PR or its already fixed as mentioned [here](https://github.com/smartsdk/ngsi-timeseries-api/issues/382#issuecomment-730264721)

**Comment by chicco785** [comment]
@daminichopra i think it's fixed, but of course if you can test and confirm would be great :)
