### ISSUE TITLE
support mismatch between DateTime (as medatata) and column type

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#386]
**Is your feature request related to a problem? Please describe.**

If something went wrong (usually due to crate dynamic columns) in the column typing w.r.t. the actual metadata type DateTime defined for a column, QL bombs. 

**Describe the solution you'd like**
It would be better to just print out the value and raise a warning.

**Describe alternatives you've considered**
Fixing manually the columns.

**Comment by c0c0n3** [comment]
closed by #387
