### ISSUE TITLE
Apply for CII Best Practices Badge

### ISSUE THREAD

**Issue by c0c0n3** [smartsdk/ngsi-timeseries-api#388]
As a FiWare GA, QL has to get a [CII Badge](https://bestpractices.coreinfrastructure.org/en)---see Jason's email about it, subject: *[Fiware-technical-committee] Applying for CII Best Practices Badge.*

I tried creating an account three times, but I never got the confirmation email from CII with the activation link. @chicco785 if you could please try creating an account with

Account Name: Martel Innovate
Email: your work email
Pass: the one I shared in passbolt

Then I'll do the rest...

**Comment by chicco785** [comment]
@c0c0n3 why not using the github account? https://bestpractices.coreinfrastructure.org/en/login

**Comment by c0c0n3** [comment]
badge owner should be martel, not c0c0n3?

**Comment by chicco785** [comment]
then also my email is not good, right?

**Comment by c0c0n3** [comment]
yea, ideally we'd use an admin-like email, e.g. admin@martel-innovate.com, if we do have one. i tried with mine@martel-innovate.com i.e. a tried to create an account in martel's name but with my email address as contact. the problem i had is that the account got created (and i can log in!) but it still isn't active since i never got the activation email in my martel inbox, so i thought there might have been a problem w/ my email since i tried recreating the account and having them resend the activation email but still no luck.

**Comment by chicco785** [comment]
no activation link arrived so far

**Comment by chicco785** [comment]
arrived now

**Comment by c0c0n3** [comment]
awesome, thanks alot. i'll take it from here. also i've found an email address we could use: info@orchestracities.com? if any of us gets emails there i could replace your email with orchestra's...

**Comment by c0c0n3** [comment]
filling out the form was a bit of a schlep but it's done and dusted now. bage linked to readme too, see 1b525f1.
