### ISSUE TITLE
Fix "similar-code" issue in client/client.py

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#39]
Similar blocks of code found in 3 locations. Consider refactoring.

https://codeclimate.com/github/smartsdk/ngsi-timeseries-api/client/client.py#issue_5a157acb9e273d0001000070

**Comment by taliaga** [comment]
Client code has been removed in https://github.com/smartsdk/ngsi-timeseries-api/pull/76
