### ISSUE TITLE
Community feedback before release 0.8

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#401]
Dear All,
before officially releasing 0.8, we would like to get your feedback on the pre-release (check https://github.com/smartsdk/ngsi-timeseries-api/releases/tag/0.8-alpha), that provides a number of interesting new features and bug fixes, including initial support for NGSI-LD.

PR #373 introduced basic support for NGSI-LD relying on v2 API. In short this means that using the current endpoint QL can store NGSI-LD payloads with few caveats. More details [here](https://github.com/smartsdk/ngsi-timeseries-api/blob/master/docs/manuals/index.md#ngsi-ld-support).
 

@agaldemas
 @blackbearst 
 @Chandradeep-NEC 
 @cnoelle
 @daminichopra 
 @ES-SC 
 @fisuda 
 @fmonsanto 
 @HaythemHorbit 
 @heikkilv
 @HOP-Ubiquitous 
 @ekatsiri 
 @iamarnavgarg 
 @iaoiui 
 @jason-fox 
 @VeroCity-UG 
 @jcheca 
 @jlohmoeller 
 @juliozinga 
 @lmreyes
 @luisdelacalle 
 @msgis 
 @ohylli 
 @PepeluDev 
 @pooja1pathak 
 @SakshiSharma-India 
 @Trigyn-Technologies 
 @vjain641 
@ilarimikkonen 
@pinkerltm
@pierre-josselin

**Comment by ilarimikkonen** [comment]
hi, more than happy to give feedback. Which Crate version would you recommend to use? and which version of Redis? We had done some initial tests with redis-cache image and the results were pretty good. When we have time, we do some load tests.

**Comment by chicco785** [comment]
@ilarimikkonen crate 4.1.4 is the base version used in the tests. We may do a version upgrade, but probably only after the release of 0.8. Redis we are using the last version: 6.0.9 (probably would be better to fix it)

**Comment by ilarimikkonen** [comment]
@chicco785 few initial questions/observations:

In our initial tests (with `redis-cache` ) we got the following results on last run:
Setup: 100 000 messages approx. 300 messages / sec.
Messages send to Orion and then with a sub to QL. Running on Kubernetes.
There was ~50% message loss with one QL and ~20% with five.
- Is 0.8 and redis-cache image any different in performance wise?
- Could you describe the architecture and behaviour of Redis caching? We saw this behaviour during testing (this is write rate: rate(container_fs_writes_bytes_total{}[5m]):
![image](https://user-images.githubusercontent.com/7221736/100206422-f916ca00-2f0e-11eb-845a-974b9133a196.png)

as you can see, we ran few times, 1st with lower load and then increasing. We have trouble understanding what Redis is doing. 

On certain load level, all messages are persisted.

**Comment by chicco785** [comment]
A bit of documentation is here:
* https://quantumleap.readthedocs.io/en/latest/#cache-back-end
You can find also tests here:
* https://quantumleap.readthedocs.io/en/latest/admin/benchmarks/

I don't think there are difference between the two images in term of performance. In short, as of today, redis is used to avoid to read every time from the db the metadata, which showed to slow down a lot inserts.

In general it is better to test ql load without orion, because that's the only way you can be sure that if you send 3000 messages, 3000 should reach ql. Recall that if for whatever reason a new message for an entity comes before it was sent the previous notification, that won't be sent.

with 1 ql and 30 sec timeout, we have no issue in processing 100 messages / sec on a laptop. surely, tweaking gunicorn configuration more can be done (but we haven't tested). Then to change significantly, probably we will need to move away from flask.

in general, as you can see here:
https://github.com/smartsdk/ngsi-timeseries-api/issues/349#issuecomment-704575150

avg response time of crate during insert is 50 msec, ql transformation and insert code adds to it only 30 msec. which lead us to think that the web server has a quite a role (see copied discussion from the comment above):

> so what's adding the 3 seconds? a profiler would be of help to get deeper, but gunicorn + flask may have quite a role in that, as well as python garbage collection. surely, fine tuning gunicorn configuration may be quite important to achieve best performance.
> 
> as said, for performance, flask seems to be not ideal and a good alternative could be https://fastapi.tiangolo.com/
> still, 105 reqs per second on a laptop does not look bad. at the time being, we will work on consolidating pr #373, but we won't invest on fastapi (we don't have a the moment a use case / customer that justify that investment).

**Comment by c0c0n3** [comment]
> avg response time of crate during insert is 50 msec, ql transformation and insert code adds to it only 30 msec

It looks like we spend the rest of the time doing network I/O---web server isn't necessarily at fault here. See https://github.com/smartsdk/ngsi-timeseries-api/issues/399#issuecomment-733708372
