### ISSUE TITLE
support keyValue mode

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#43]
I suppose that using a parser it is possible to use also the keyValue mode.
Orion is supporting it, so there should be no reason for QL not being able to to so.

**Comment by chicco785** [comment]
e.g.
if input in int
   Integer
if input in float
   Number
if input in boolean
    Boolean
if input in string:
      if input match DateTime regex
         DateTime
      else
          Text

**Comment by taliaga** [comment]
related: https://github.com/smartsdk/ngsi-timeseries-api/issues/141
