### ISSUE TITLE
Document considerations when directly inserting into QL

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#46]
Some usecases may not use Orion, so expected data format should be well documented in QL.

**Comment by iamarnavgarg** [comment]
Hi @taliaga , As per my understanding, I think the information for adding the data to QL is using `/v2/notify `API and should be placed at location -[Here]( https://github.com/smartsdk/ngsi-timeseries-api/blob/master/docs/manuals/user/index.md)

**Comment by c0c0n3** [comment]
Fixed by #268
