### ISSUE TITLE
Query api follow-ups

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#60]
- [x] Better treatment for missing "type" param in the query
- [x] Add test to make sure a reasonable response is returned when no entity matches any of the supported queries

**Comment by c0c0n3** [comment]
look at reporter/query_*.py modules.

**Comment by c0c0n3** [comment]
there's a `test_not_found` test for each supported query type that checks QL returns a 404 when there's no matching entity. (code in v0.4.1rc)
