### ISSUE TITLE
Add status endpoint

### ISSUE THREAD

**Issue by taliaga** [smartsdk/ngsi-timeseries-api#68]
Add some form of status endpoint, which could be used in liveness/readiness Probes that reports on the status of complementing services (crate, maybe grafana and redis)

**Comment by chicco785** [comment]
1. can connect to the db -> fail red (500)
2. can query the db -> fail red (500)
3. can connect to redis -> fail orange (200)
4. can query redis -> fail orange (200)
5. can query geocoding api -> fail orange (200)

```
"status": {
  "db-connection": 1,
  "db-query": 1,
  "cache-connection": 1,
  "cache-query": 1,
  "geocoding-query": 1,
  "timestamp": "xxx"
}
```
