### ISSUE TITLE
Problems with aggrPeriod attribute

### ISSUE THREAD

**Issue by Racso93** [smartsdk/ngsi-timeseries-api#89]
I'm trying to use the aggrPeriod attribute in a query to /entitites/../attrs/...? and I do not know if it does not work or that I have a wrong idea about him.

In my opinion, if I add the attribute "aggrPeriod = minute" with the method "aggrMethod = avg", the query will return me the value of the values, minute by minute.

Is this what should happen?

**Comment by taliaga** [comment]
Hi! You are correct in your interpretation, and you have brought to our attention an important point. 

The `aggrPeriod` was not yet implemented and this is not clearly visible in the API nor in the return of the call. This is definitively wrong. So, I've made this clearer in the API in (https://github.com/smartsdk/ngsi-timeseries-api/pull/90). Given that you need this, I'll try to get it implemented as soon as possible, at least for `/entitites/.../attrs/...`.

Thanks for opening this!

**Comment by Racso93** [comment]
Hi!

Thank you very much for the information.

Actually I was only doing some tests to see how far the API came, so for my part it is not necessary that you get with the implementation of `aggrPeriod`.

Thanks, again.
