### ISSUE TITLE
it looks that values can be only Number

### ISSUE THREAD

**Issue by chicco785** [smartsdk/ngsi-timeseries-api#96]
https://github.com/smartsdk/ngsi-timeseries-api/blob/363450fb3ced2c1597b36342f0e96dc8797f8a61/specification/quantumleap.yml#L87

**Comment by c0c0n3** [comment]
see also #36

**Comment by taliaga** [comment]
Duplicated of / Covered by https://github.com/smartsdk/ngsi-timeseries-api/issues/147
